// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Category struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Student struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Studentdiscord struct {
	StudentID int32        `json:"student_id"`
	DiscordID string       `json:"discord_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Studentsubjectcompletion struct {
	ID          int32        `json:"id"`
	StudentID   int32        `json:"student_id"`
	SubjectID   int32        `json:"subject_id"`
	CompletedAt sql.NullTime `json:"completed_at"`
}

type Studenttutor struct {
	ID        int32     `json:"id"`
	StudentID int32     `json:"student_id"`
	TutorID   int32     `json:"tutor_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Subject struct {
	ID          int32          `json:"id"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Class       string         `json:"class"`
}

type Subjectcategory struct {
	ID         int32 `json:"id"`
	SubjectID  int32 `json:"subject_id"`
	CategoryID int32 `json:"category_id"`
}

type Tutor struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Tutordiscord struct {
	TutorID   int32        `json:"tutor_id"`
	DiscordID string       `json:"discord_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}
