// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reset.sql

package database

import (
	"context"
)

const resetCategories = `-- name: ResetCategories :exec
delete from Categories
`

func (q *Queries) ResetCategories(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetCategories)
	return err
}

const resetSC = `-- name: ResetSC :exec
delete from SubjectCategory
`

func (q *Queries) ResetSC(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSC)
	return err
}

const resetSD = `-- name: ResetSD :exec
delete from StudentDiscords
`

func (q *Queries) ResetSD(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSD)
	return err
}

const resetSSC = `-- name: ResetSSC :exec
delete from StudentSubjectCompletion
`

func (q *Queries) ResetSSC(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSSC)
	return err
}

const resetST = `-- name: ResetST :exec
delete from StudentTutor
`

func (q *Queries) ResetST(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetST)
	return err
}

const resetStudents = `-- name: ResetStudents :exec
delete from Students
`

func (q *Queries) ResetStudents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetStudents)
	return err
}

const resetSubjects = `-- name: ResetSubjects :exec
delete from Subjects
`

func (q *Queries) ResetSubjects(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetSubjects)
	return err
}

const resetTD = `-- name: ResetTD :exec
delete from TutorDiscords
`

func (q *Queries) ResetTD(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetTD)
	return err
}

const resetTutors = `-- name: ResetTutors :exec
delete from Tutors
`

func (q *Queries) ResetTutors(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetTutors)
	return err
}
