// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tutors.sql

package database

import (
	"context"
	"database/sql"
)

const createTutor = `-- name: CreateTutor :execresult
insert into Tutors (name) value (?)
`

func (q *Queries) CreateTutor(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTutor, name)
}

const getAllTutors = `-- name: GetAllTutors :many
select id, name from Tutors
`

func (q *Queries) GetAllTutors(ctx context.Context) ([]Tutor, error) {
	rows, err := q.db.QueryContext(ctx, getAllTutors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tutor{}
	for rows.Next() {
		var i Tutor
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTutorsWithNameLike = `-- name: GetAllTutorsWithNameLike :many
select id, name from Tutors
where name like ?
`

func (q *Queries) GetAllTutorsWithNameLike(ctx context.Context, name string) ([]Tutor, error) {
	rows, err := q.db.QueryContext(ctx, getAllTutorsWithNameLike, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tutor{}
	for rows.Next() {
		var i Tutor
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTutorByID = `-- name: GetTutorByID :one
select id, name from Tutors
where id = ?
`

func (q *Queries) GetTutorByID(ctx context.Context, id int32) (Tutor, error) {
	row := q.db.QueryRowContext(ctx, getTutorByID, id)
	var i Tutor
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateTutor = `-- name: UpdateTutor :execresult
update Tutors
set name = ?
where id = ?
`

type UpdateTutorParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateTutor(ctx context.Context, arg UpdateTutorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTutor, arg.Name, arg.ID)
}
